config/routes.rb
Rails.application.routes.draw do
  get 'home', to: 'pages#home'
  get 'about-us', to: 'pages#about_us'
  get 'services', to: 'pages#services'
  get 'contact-us', to: 'admin/users#new'
  post 'contact-us', to: 'admin/users#create'
  get 'contact-requests', to: 'admin/users#index'

  namespace :admin do
    resources :admins do
      member do
        patch :disable
        patch :enable
      end
    end
  end

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  root 'pages#home'
end

app/models/admin.rb
class Admin < ApplicationRecord

  has_secure_password

  validates :name, :email, presence: true
  validates :email, format: /[a-z]+\w*@[a-z]{3,}(.[a-z]{2,5}){1,2}/i, allow_blank: true
  validates :email, uniqueness: { case_sensitive: false }, allow_blank: true

  after_create :send_welcome_mail

  private

    def send_welcome_mail
      AdminMailer.welcome(id).deliver_now
    end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, :email, :message, presence: true

  after_commit :notify_admins, on: :create

  private

    def notify_admins
      UserMailer.notify(id).deliver_now
    end
end

app/controllers/admin/admins_controller.rb
class Admin::AdminsController < ApplicationController
  layout 'admin'

  before_action :check_for_current_admin
  before_action :load_admin, only: [:show, :edit, :update, :destroy, :disable, :enable]

  def new
    @admin = Admin.new
  end

  def create
    @admin = Admin.new(admin_params)
    if @admin.save
      redirect_to admin_admins_path, notice: "You have successfully created #{@admin.name}."
    else
      render :new
    end
  end

  def index
    @admins = Admin.all.order(:created_at)
  end

  def update
    if @admin.update(admin_params)
      redirect_to admin_admins_path, notice: "You have successfully updated #{@admin.name}."
    else
      render action: 'edit'
    end
  end

  def destroy
    if @admin.destroy
      flash[:notice] = "You have successfully destroyed #{@admin.name}."
    else
      flash[:alert] = "Error updating #{@admin.name}. Please try again."
    end
    redirect_to admin_admins_path
  end

  def disable
    if @admin.disable!
      flash[:notice] = "You have successfully disabled #{@admin.name}."
    else
      flash[:alert] = "Error disabling #{@admin.name}. Please try again."
    end
    redirect_to admin_admins_path
  end

  def enable
    if @admin.enable!
      flash[:notice] = "You have successfully enabled #{@admin.name}."
    else
      flash[:alert] = "Error enabling #{@admin.name}. Please try again."
    end
    redirect_to admin_admins_path
  end

  private

    def check_for_current_admin
      redirect_to login_path, alert: 'Please log in first' unless current_admin
    end

    def load_admin
      @admin = Admin.where(id: params[:id]).first
      unless @admin
        redirect_to admin_admins_path, alert: 'Admin not found!'
      end
    end

    def admin_params
      params.require(:admin).permit(:name, :password, :password_confirmation, :email)
    end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  layout 'admin', only: [:index]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to contact_us_path, notice: 'Thank you for getting in touch! We will get back to you soon! :)'
    else
      flash[:alert] = 'Please provide all required fields.'
      render :new
    end
  end

  def index
    @users = User.all.order(:created_at)
  end

  private

    def user_params
      params.require(:user).permit(:name, :contact_number, :email, :message)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def current_admin
    @current_admin ||= Admin.find_by(id: session[:admin_id])
  end
  helper_method :current_admin
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  layout 'admin'

  def new
    redirect_to contact_requests_path if session[:admin_id]
  end

  def create
    @admin = Admin.find_by(email: params[:email])
    if @admin && @admin.authenticate(params[:password])
      session[:admin_id] = @admin.id
      redirect_to contact_requests_path, notice: 'You have successfully signed in.'
    else
      redirect_to login_path, alert: 'Error logging in!'
    end
  end

  def destroy
    session[:admin_id] = nil
    redirect_to login_path, notice: 'Logged out successfully.'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/admins/_admin.html.erb
<tbody>
  <tr>
    <td><%= admin.id %></td>
    <td><%= admin.name %></td>
    <td><%= admin.email %></td>
    <td><%= admin.created_at.strftime("%d-%m-%Y") %></td>
    <td><%= link_to 'View', admin_admin_path(admin) %></td>
    <td><%= link_to 'Edit', edit_admin_admin_path(admin) %></td>
    <% if admin.enabled %>
      <td><%= link_to 'Disable', disable_admin_admin_path(admin), method: :patch,  data: { confirm: 'Do you want to disable the admin?' }  %></td>
    <% else %>
      <td><%= link_to 'Enable', enable_admin_admin_path(admin), method: :patch,  data: { confirm: 'Do you want to enable the admin?' }  %></td>
    <% end %>
    <td><%= link_to image_tag('delete-icon.png', class: 'delete-icon'), admin_admin_path(admin), method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
</tbody>

app/views/admin/admins/_form.html.erb
<div class="bs-docs-section">
  <div class="row">
    <% if @admin.errors %>
      <ul>
        <% @admin.errors.full_messages.each do |msg| %>
          <li class="text-danger"><%= msg %></li>
        <% end %>
      </ul>
    <% end %>
    <div class="col-lg-6">
      <div class="well bs-component">
        <%= form_for [:admin, @admin], html: { class: "form-horizontal" } do |f| %>
          <fieldset>
            <legend>Enter admin details</legend>
            <div class="form-group">
              <%= f.label :name, 'Name *:', class: "col-lg-3 control-label" %>
              <div class="col-lg-9">
                <%= f.text_field :name, class: "form-control" %>
              </div>
            </div>
            <div class="form-group">
              <%= f.label :email, 'Email *:', class: "col-lg-3 control-label" %>
              <div class="col-lg-9">
                <%= f.text_field :email, class: "form-control" %>
              </div>
            </div>
            <div class="form-group">
              <%= f.label :password, 'Password *:', class: "col-lg-3 control-label" %>
              <div class="col-lg-9">
                <%= f.text_field :password, class: "form-control" %>
              </div>
            </div>
            <div class="form-group">
              <%= f.label :password_confirmation, 'Password confirmation *:', class: "col-lg-3 control-label" %>
              <div class="col-lg-9">
                <%= f.text_field :password_confirmation, class: "form-control" %>
              </div>
            </div>
            <div class="col-lg-9 col-lg-offset-3">
              <% if @admin.new_record? %>
                <%= f.submit 'Create', class: "btn btn-primary" %>
              <% else %>
                <%= f.submit 'Update', class: "btn btn-primary" %>
              <% end %>
              <%= link_to 'Back', admin_admins_path, class: "btn btn-primary btm-sm" %>
            </div>
          </fieldset>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/admin/admins/edit.html.erb
<div class="container">
  <h2>Update Admin</h2>
  <%= render 'form' %>
</div>

app/views/admin/admins/index.html.erb
<div class="container">
  <div class="bs-docs-section">
    <div class="row">
      <div class="col-lg-12">
        <h2>Admins</h2>
        <%= link_to 'Create Admin', new_admin_admin_path, class: "btn btn-primary btn-sm pull-right" %>
      </div>
      <div class="row">
        <div class="col-lg-12">
          <div class="bs-component">
            <table class="table table-striped table-hover ">
              <thead>
                <tr class='success'>
                  <th>#</th>
                  <th>Name</th>
                  <th>Email</th>
                  <th>Created At</th>
                  <th></th>
                  <th></th>
                  <th>Actions</th>
                  <th></th>
                </tr>
              </thead>
              <% if @admins.empty? %>
                <p class="lead text-info">No admins found!</p>
              <% else %>
                <%= render @admins %>
              <% end %>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/admins/new.html.erb
<div class="container">
  <h2>New Admin</h2>
  <%= render 'form' %>
</div>

app/views/admin/admins/show.html.erb
<div class="container">
  <h2>Admin Details</h2>
  <div class="bs-docs-section">
    <div class="row">
      <div class="col-lg-12">
       <div>
         <strong>Name:</strong>
         <span><%= @admin.name %></span>
       </div>
       <div>
         <strong>Email:</strong>
         <span><%=@admin.email %></span>
       </div>
       <div>
         <strong>Created At:</strong>
         <span><%=@admin.created_at.strftime("%v") %></span>
       </div>
      </div>
    </div>
    <br>
    <%= link_to "Back", admin_admins_path, class: "btn btn-primary btn-sm" %>
  </div>
</div>

app/views/admin/users/_form.html.erb
<div class="bs-docs-section">
  <div class="row">
    <div class="col-lg-12">
      <div class="well bs-component">
        <%= form_for @user, url: contact_us_path, html: { class: "form-horizontal" } do |f| %>
          <fieldset>
            <div class="form-group">
              <%= f.label :name, 'Name *:', class: "col-lg-4 control-label" %>
              <div class="col-lg-8">
                <%= f.text_field :name, class: "form-control" %>
              </div>
            </div>
            <div class="form-group">
              <%= f.label :email, 'Email *:', class: "col-lg-4 control-label" %>
              <div class="col-lg-8">
                <%= f.text_field :email, class: "form-control" %>
              </div>
            </div>
            <div class="form-group">
              <%= f.label :contact_number, 'Contact Number:', class: "col-lg-4 control-label" %>
              <div class="col-lg-8">
                <%= f.text_field :contact_number, class: "form-control" %>
              </div>
            </div>
            <div class="form-group">
              <%= f.label :message, 'Message *:', class: "col-lg-4 control-label" %>
              <div class="col-lg-8">
                <%= f.text_area :message, rows: 8, class: "form-control" %>
              </div>
            </div>
            <div class="col-lg-8 col-lg-offset-1">
              <%= f.submit 'Submit', class: "btn btn-primary" %>
            </div>
          </fieldset>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/admin/users/_user.html.erb
<tbody>
  <tr>
    <td><%= user.id %></td>
    <td><%= user.name %></td>
    <td><%= user.email %></td>
    <td><%= user.contact_number %></td>
    <td><%= user.message %></td>
    <td><%= user.created_at.strftime("%d-%m-%Y") %></td>
  </tr>
</tbody>

app/views/admin/users/index.html.erb
<div class="container">
  <div class="bs-docs-section">
    <div class="row">
      <div class="col-lg-12">
        <h2>Contact Requests</h2>
      </div>
      <div class="row">
        <div class="col-lg-12">
          <div class="bs-component">
            <% if @users.empty? %>
              <p class="lead text-info">No requests found!</p>
            <% else %>
              <table class="table table-striped table-hover ">
                <thead>
                  <tr class='success'>
                    <th>#</th>
                    <th>Name</th>
                    <th>Email</th>
                    <th>Email</th>
                    <th>Email</th>
                    <th>Sent At</th>
                  </tr>
                </thead>
                  <%= render @users %>
              </table>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/users/new.html.erb
<div class="static_page">
  <div class="container contact">
    <h1 class="page_title">
      <span class="icon_tech_info"></span>
      Technophile Infotech
    </h1>
    <h3>your one stop destination for all <span class="bold">IT solutions</span></h3>

    <h2 class='title'>get in touch</h2>
    <%= render "layouts/flash_messages" %>
    <div class="col-lg-6">
      <div class="addresses">
        <script src='https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false&key=AIzaSyABrsjXrfE8tIBx7Y2ZKTYcvP8zdyxWvxc'></script><div style='overflow:hidden;height:440px;width:540px;'><div id='gmap_canvas' style='height:440px;width:540px;'></div><div><small><a href="http://embedgooglemaps.com">                 embed google map              </a></small></div><div><small><a href="http://googlemapsgenerator.com">googlemapsgenerator.com</a></small></div><style>#gmap_canvas img{max-width:none!important;background:none!important}</style></div><script type='text/javascript'>function init_map(){var myOptions = {zoom:12,center:new google.maps.LatLng(28.6390693,77.08677409999996),mapTypeId: google.maps.MapTypeId.ROADMAP};map = new google.maps.Map(document.getElementById('gmap_canvas'), myOptions);marker = new google.maps.Marker({map: map,position: new google.maps.LatLng(28.6390693,77.08677409999996)});infowindow = new google.maps.InfoWindow({content:'<strong>Technophile Infotech</strong><br>G56,, Gali Number 15, Raj Nagar Part II, Palam Colony, New Delhi, Delhi 110045,India<br>'});google.maps.event.addListener(marker, 'click', function(){infowindow.open(map,marker);});infowindow.open(map,marker);}google.maps.event.addDomListener(window, 'load', init_map);</script>
      </div>
    </div>
    <div class="col-lg-6">
      <%= render 'form' %>
    </div>
  </div>
  <%= render partial: 'share/footer' %>
</div>

app/views/layouts/_flash_messages.html.erb
<div class="container" id="flash-message">
  <% if notice %>
    <p class="alert alert-dismissable alert-success">
      <button type="button" class="close" data-dismiss="alert">×</button>
      <%= notice %>
    </p>
  <% elsif alert %>
    <p class="alert alert-dismissable alert-danger">
      <button type="button" class="close" data-dismiss="alert">×</button>
      <%= alert %>
    </p>
  <% end %>
</div>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Technophile Infotech</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= favicon_link_tag %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="bs-docs-section clearfix">
      <div class="bs-component">
        <div class="navbar navbar-default">
          <div class="container">
            <div class="navbar-header">
              <button typeclass: "btn btn-primary btn-xs"="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <%= link_to "Technophile Infotech", root_path, class: "navbar-brand" %>
            </div>
            <% if current_admin %>
              <div class="navbar-collapse collapse navbar-responsive-collapse">
                <ul class="nav navbar-nav">
                  <li><%= link_to "Admins", admin_admins_path, class: ('page-active' if (root_path)) %></li>
                  <li><%= link_to "Contact Requests", contact_requests_path, class: ('page-active' if (root_path)) %></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                  <li class="text-success">
                    <%= link_to "Welcome #{ current_admin.name }!", admin_admin_path(current_admin), class: "#{ ((current_admin)) }" if current_admin %>
                  </li>
                  <li><%= link_to 'Sign Out', logout_path, method: :delete, class: "btn btn-primary btn-xs" %></li>
                </ul>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
    <%= render "layouts/flash_messages" %>
    <%= yield %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Technophile Infotech</title>
    <%= stylesheet_link_tag    'home/home', media: 'all' %>
    <%= javascript_include_tag 'home' %>
    <%= favicon_link_tag %>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= favicon_link_tag %>
  </head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/about_us.html.erb
<div class="static_page">
  <div class="container about">
    <h1 class="page_title">
      <span class="icon_tech_info"></span>
      Technophile Infotech
    </h1>
    <h3>your one stop destination for all <span class="bold">IT solutions</span></h3>

    <h2 class="title">About</h2>
    <p>
      Technophile Infotech is a recent venture by a team of spirited and vibrant tech enthusiasts. We aim to provide holistic technical expertise to clientele, at a reasonable price.


    </p>
  </div>

  <%= render partial: 'share/footer' %>
</div>

app/views/pages/home.html.erb
<div  id="overlay" class="text-center vertical-center">
  <%#= render partial: 'share/footer' %>
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-sm-8 pull-left" id="download">
        <a target="_blank" href="#" class="tech-info">
          Technophile Infotech
        </a>
      </div>
      <div class="col-xs-10 col-xs-offset-1 col-sm-4 col-sm-offset-1 pull-right">
        <div id="phone_wrapper">
          <div id="phone_container">
            <div id="images" class="slider">
              <section><img src="assets/home/ti.png"></section>
              <section><img src="assets/home/ti.png"></section>
              <section><img src="assets/home/we24x7.png"></section>
              <section>
                <a href="">
                  <script src='https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false&key=AIzaSyABrsjXrfE8tIBx7Y2ZKTYcvP8zdyxWvxc'></script><div style='overflow:hidden;height:454px;width:255px;'><div id='gmap_canvas' style='height:454px;width:255px;'></div><div><small><a href="http://embedgooglemaps.com">                 embed google map              </a></small></div><div><small><a href="http://googlemapsgenerator.com">googlemapsgenerator.com</a></small></div><style>#gmap_canvas img{max-width:none!important;background:none!important}</style></div><script type='text/javascript'>function init_map(){var myOptions = {zoom:12,center:new google.maps.LatLng(28.6390693,77.08677409999996),mapTypeId: google.maps.MapTypeId.ROADMAP};map = new google.maps.Map(document.getElementById('gmap_canvas'), myOptions);marker = new google.maps.Marker({map: map,position: new google.maps.LatLng(28.6390693,77.08677409999996)});infowindow = new google.maps.InfoWindow({content:'<strong>Technophile Infotech</strong><br>G56,, Gali Number 15, Raj Nagar Part II, Palam Colony, New Delhi, Delhi 110045,India<br>'});google.maps.event.addListener(marker, 'click', function(){infowindow.open(map,marker);});infowindow.open(map,marker);}google.maps.event.addDomListener(window, 'load', init_map);</script>
              </section>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<ul class="nav" id="nav">
  <li data-menuanchor='tech_info'><a href="#tech_info" ></a></li>
  <li data-menuanchor='discover'><a href="#discover"></a></li>
  <li data-menuanchor='track'><a href="#track"></a></li>
  <li data-menuanchor='share'><a href="#share"></a></li>
</ul>
<div id="page_wrapper" class="slider" >
  <section id="tech_info_section" class="section text-center vertical-center ">
    <div class="container">
      <div class="row">
        <div class="col-xs-12 col-sm-8 pull-left">
          <div class="icon"></div>
          <h1>technophile infotech</h1>
          <p>your one stop destination for all</p>
          <p class="bold">IT solutions</p>
        </div>
      </div>
    </div>
  </section>
  <section id="discover_section" class="section text-center vertical-center ">
    <div class="container">
      <div class="row">
        <div class="col-xs-12 col-sm-8 pull-left">
          <div class="icon"></div>
          <h1>discover</h1>
          <p>the joy of par excellence sevice.<br />just sit back and relax,<br /><b>we'll take care of it!</b></p>
        </div>
      </div>
    </div>
  </section>
  <section id="track_section" class="section text-center vertical-center ">
    <div class="container">
      <div class="row">
        <div class="col-xs-12 col-sm-8 pull-left">
          <div class="icon"></div>
          <h1>24 x 7 availability</h1>
          <p>be it emergency services<br />or long-term associations<br />you need not worry<br /><b>we are just a call away!</b></p>
        </div>
      </div>
    </div>
  </section>
  <section id="share_section" class="section text-center vertical-center ">
    <div class="container">
      <div class="row">
        <div class="col-xs-12 col-sm-8 pull-left">
          <h1>get in touch</h1>
          <div class="links">
            <a href="https://www.facebook.com/technophileinfotech3" class="fb" target="_blank"></a>
            <a href="https://www.twitter.com/technophileinfo" class="tw" target="_blank"></a>
          </div>
        </div>
      </div>
    </div>
  <%= render partial: 'share/footer' %>
  </section>
</div>

app/views/pages/services.html.erb
<div class="static_page services">
  <div class="container about">
    <div class="services-header">
      <h1 class="page_title">
        <span class="icon_tech_info"></span>
        Technophile Infotech
      </h1>
      <h3>your one stop destination for all <span class="bold">IT solutions</span></h3>

      <h2 class="title">services</h2>
    </div>

    <div class="row">
      <div class="col-xs-12  col-md-12 row">
        <div class="col-md-6 page-box page-box--block">
          <%= image_tag 'demo/content/content_1.png', alt: 'Technophile Infotech', width: '360px', height: '240px' %>
          <div class="page-box__content">
            <h3 class="page-box__title  text-uppercase">
              Deals in IT Hardware
            </h3>
            <ul style="list-style: none;">
              <li>
                Servers – All brands
              </li>
              <li>
                Backup Devices
              </li>
              <li>
                Desktops – All brands
              </li>
              <li>
                Laptops – All brands
              </li>
              <li>
                Switches – Cisco and D-Links
              </li>
              <li>
                Routers – Cisco
              </li>
            </ul>
          </div>
        </div>

        <div class="col-md-6 page-box page-box--block">
          <%= image_tag 'demo/content/content_2.jpg', alt: 'Technophile Infotech', width: '360px', height: '240px' %>
          <div class="page-box__content">
            <h3 class="page-box__title text-uppercase">
              Deals in IT Software
            </h3><ul style="list-style: none;">
              <li>
                Microsoft Windows Software
              </li>
              <li>
                Linux
              </li>
              <li>
                Oracle
              </li>
              <li>
                SQL
              </li>
              <li>
                Backup Storage
              </li>
            </ul>
          </div>
        </div>
      </div>

      <div class="col-xs-12  col-md-12 row">
        <div class="col-md-6 page-box page-box--block">
          <%= image_tag 'demo/content/content_4.jpg', alt: 'Technophile Infotech', width: '360px', height: '240px' %>
          <div class="page-box__content">
            <h3 class="page-box__title text-uppercase">
              Deals in IT Services
            </h3>
            <ul style="list-style: none;">
              <li>
                FMS- Facility Management Service
              </li>
              <li>
                AMC- Annual Maintenance Contract
              </li>
            </ul>
          </div>
        </div>

        <div class="col-md-6 page-box page-box--block">
          <%= image_tag 'demo/content/cctv-4.jpg', alt: 'Technophile Infotech', width: '360px', height: '240px' %>
          <div class="page-box__content">
            <h3 class="page-box__title text-uppercase">
              Deals in Trunky Projects
            </h3>
            <ul style="list-style: none;">
              <li>
                Office Networking
              </li>
              <li>
                Access Control
              </li>
              <li>
                CCTVs
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
  <%= render partial: 'share/footer' %>
</div>

app/views/share/_footer.html.erb
<div class="web_nav">
  <%= image_tag 'tech_info.png', class: 'logo' %>
  <ul>
    <li><%= link_to 'Home' , root_url %></li>
    <li><%= link_to'About', '/about-us'%></li>
    <li><%= link_to'Services', '/services'%></li>
    <li><%= link_to'Contact Us', '/contact-us'%></li>
  </ul>
</div>